server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://ec2-13-247-97-16.af-south-1.compute.amazonaws.com:8091
          predicates:
            - Path=/api/v1/auth/**