name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build Project
        run: mvn clean install -DskipTests

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t damuleli/gateway-service .

      - name: Publish image to Docker Hub
        run: docker push damuleli/gateway-service

  deploy:
    needs: build
    runs-on: [aws-ec2]  # Ensure you have a self-hosted runner labeled 'aws-ec2'

    steps:
      - name: Pull the image from Docker Hub
        run: docker pull damuleli/gateway-service:latest

      - name: Delete old containers
        run: docker rm -f gateway-service-container || true  # Ignore error if the container does not exist

      - name: Run Docker as container
        run: docker run -d -p 8080:8080 --name gateway-service-container damuleli/gateway-service

      - name: Verify Docker Installation
        run: |
          echo "Checking Docker version..."
          docker --version